### ISSUE TITLE
Extension to multi-dimensional array (proposal)

### ISSUE THREAD

**Issue by kokitsuyuzaki** [LTLA/TileDBArray#22]
Thanks for the great work.
I'd like to use `TileDBArray` against a multi-dimensional array as follows but this code was failed with an error.

```
library(TileDBArray)

mat <- as(array(rbinom(5*6, 2, 0.1), c(5,6)), "TileDBArray")
arr <- as(array(rbinom(5*6*7, 2, 0.1), c(5,6,7)), "TileDBArray")
```

If this code could be performed, we can accelerate not only matrix decomposition algorithms but also tensor decomposition algorithms, just like Aaron Lun accelerated the `runPCA` by using TileDBArray before.
https://www.youtube.com/watch?v=wQJbSh-NHeg&t=1819s

Could you extend `TileDBArray` to multi-dimensional array?

**Comment by eddelbuettel** [comment]
(Not speaking for @LTLA here but ....) this looks like a very useful suggestion. Happy to help from my side as support easier use of matrices was just added which I could easily extend to 3-d arrays (and I mostly held back because a) the default print methods are so verbose and b) I was unsure of user needs.  This shows one, so happy to help.

**Comment by LTLA** [comment]
Doesn't it already? Works fine for me, aside from a few warning messages about the deprecation of `tiledb_dense`.

```
> library(TileDBArray)
> mat <- as(array(rbinom(5*6, 2, 0.1), c(5,6)), "TileDBArray")
> arr <- as(array(rbinom(5*6*7, 2, 0.1), c(5,6,7)), "TileDBArray")
> mat
<5 x 6> matrix of class TileDBMatrix and type "integer":
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    0    0    0    0    1
[2,]    1    0    0    0    0    0
[3,]    0    0    0    0    0    0
[4,]    0    0    0    0    1    0
[5,]    0    0    1    1    0    0
> arr
<5 x 6 x 7> array of class TileDBArray and type "integer":
,,1
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    0    1    0    0    0
[2,]    0    0    0    0    0    0
[3,]    0    0    0    0    0    0
[4,]    0    0    0    1    1    1
[5,]    0    0    0    1    1    0

...

,,7
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    1    0    0    0    0
[2,]    0    0    0    0    1    0
[3,]    1    0    0    1    0    0
[4,]    0    0    0    0    0    0
[5,]    1    0    0    1    0    0
```

Getting rid of the deprecation warnings seems like it will require a little bit of work; `tiledb_array` is not a drop-in replacement for `tiledb_dense` and `tiledb_sparse`.

**Comment by kokitsuyuzaki** [comment]
I updated the TileDBArray version from 1.0.0 to 1.1.3 and my code finally worked!
Thank you @eddelbuettel and @LTLA so much for the great job!

**Comment by kokitsuyuzaki** [comment]
@eddelbuettel Does this mean that this change will be available on DelayedTensor in the next release of Bioconductor 3.13?

**Comment by eddelbuettel** [comment]
@kokitsuyuzaki That is a question for @LTLA who stands behind the BioConductor package `TileDBArray`.  I cover things over at CRAN in the package `tiledb` it uses.  

But I think the answer is yes as BioConductor generally accumulates changes until a release is made, usually bi-annually.
