### ISSUE TITLE
How to create a huge on-disk array directly from R

### ISSUE THREAD

**Issue by kokitsuyuzaki** [LTLA/TileDBArray#23]
To analyze a huge multi-dimensional array, I checked some on-disk implementations such as `DelayedArray`, `HDF5Array`, and `TileDBArray` but all of them seem to assume that a huge array is already stored in HDF5 or TileDB and if we want to create an on-disk array in R, we can create only a small array that can fit in memory.

For example, in the code below, `small_arr` can be created but large_arr cannot be created because we have to create a huge in-memory array first and then it will be converted to `RleArray`.

```R
library("TileDBArray")
small_arr <- as(array(runif(10*20*30), c(10,20,30)), "TileDBArray")
large_arr <- as(array(runif(10000*1000*1000), c(10000,1000,1000)), "TileDBArray")
```

Can I create a `TileDBArray` without defining the intermediate array object?
Perhaps, does using new (constractor) solve this problem?
https://github.com/LTLA/TileDBArray/blob/469ad477922e52894e6874391f3a97039f598f7b/R/TileDBArray.R#L123-L124

**Comment by eddelbuettel** [comment]
You can take advantage of the fact that the `TileDBArray` package uses the exact same representation on disk as the `tiledb` R package on CRAN --- or _any_ other TileDB interface (_i.e._ you could also write the array to disk in Python or Go or C++ or ... and retrieve it).  

For a recent geospatial example I wrote over a hundred LiDAR LAS data files in a loop to a single sparse array with three indices, resulting in one large sparse array of several gb compressed, which is easily accessible efficiently.  That used a domain-specific writer but the _idea_ is the same:  create a schema with the dimensions and attributes you care about, then write to it, possible in several batches.  It is important here to set the right _domain_ (minimum and maximum value). You can leave this at 'minus infiinty' and 'plus infinity' (using either `int` or `numeric` negative and positive `max`). The tile extent value also matters, but mostly for efficiency.  Different values work, you can experiement and time; a fixed value like 1000 or 10000 is also a fair choice (depending on your data, really).

You can set those explicitly when you create your array representation. We can probably set up a mock example with a schema creation and then two or three or ... writes standing in for an example with many more.

**Comment by kokitsuyuzaki** [comment]
I'm not familiar with TileDB but does that mean I can use `tiledb` to do that?
I guess it's a good idea to write something called schema first.
I'll check the document of `tiledb`.

**Comment by eddelbuettel** [comment]
Yes, with the standard semantics of the underlying TileDB you can open an array and append to it. I am less familiar with how the DelayedArray familiy in BioConductor is setup, and I am not seeing a relevant example so I made a quick one up here.

First, we write a (sparse, could be dense too) TileDBArray (which subclasses from DelayedArray):

```r
library(TileDBArray)
set.seed(123)
x1 <- Matrix::rsparsematrix(1000, 1000, density=0.01)
out1 <- writeTileDBArray(x1, "/tmp/tiledb/tiledbarrayExample", sparse=TRUE)
```

Next, we use TIleDB to append to the array

```
library(tiledb)
arr <- tiledb_array("/tmp/tiledb/tiledbarrayExample", as.data.frame=TRUE)
head(arr[])                  # glance at some elements, here in data.frame representation
dim(arr[])                   # 10k elements

x3 <- data.frame(d1=sample(1000, 100, replace=TRUE),
                 d2=sample(1000, 100, replace=TRUE),
                 x=rnorm(100))
arr[] <- x3                  # append to existing array

dim(arr[])                   # now more elements
```

Hope this helps,  @LTLA can probably help you more with TileDBArray, I am more than happy to help with TileDB itself.

**Comment by LTLA** [comment]
**TileDBArray** uses the same realization sink philosophy as discussed in Bioconductor/HDF5Array#41, you should be able to apply the same solution there, just swapping a `HDF5RealizationSink` with a `TileDBRealizationSink`. There is no obligation to represent the incoming matrix fully in memory, our examples and documentation just do so for convenience.

**Comment by kokitsuyuzaki** [comment]
Thanks, @eddelbuettel and @LTLA

This functionality is really great.
I'll check the document of `tiledb` and `TileDBRealizationSink`.
