### ISSUE TITLE
Thoughts on using tiledb_array

### ISSUE THREAD

**Issue by LTLA** [LTLA/TileDBArray#9]
Having played around with `tiledb_array` on 0.7.0, here are some thoughts on its integration with `TileDBArray`. I will use the following example to provide some context:

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 5L))
d2  <- tiledb_dim("d2", domain = c(1L, 5L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val))
tiledb_array_create(tmp, sch)

A <- tiledb_array(uri = tmp)
A[] <- data.frame(d1=rep(1:5,5), d2=rep(1:5,each=5), val=1:25)
```

## Error when the index is a symbol

There's some odd `substitute()` calls inside the `[` method that probably causes this:

```r
A[list(c(1,2), c(4,5)),] 
## $d1
##  [1] 1 1 1 1 1 2 2 2 2 2 4 4 4 4 4 5 5 5 5 5
## 
## $d2
##  [1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
## 
## $val
##  [1]  1  6 11 16 21  2  7 12 17 22  4  9 14 19 24  5 10 15 20 25

Y <- list(c(1,2), c(4,5))
A[Y,]
## Error in is[[1]] : object of type 'symbol' is not subsettable
```

This blocks programmatic usage for the time being.

## Preferred subset output

In fact, it doesn't even have to be the `[` function, you could give me an entirely different function that does this. Let's call it `tiledb_extract_indices()` for now. For the inputs, I would like:

- the `tiledb_array` object `x`, let's say with N dimensions.
- one or more indexing arguments, say `i` for the first dimension, `j` and so on. These would be integer vectors (or `NULL`, if we want all of that dimension).

For outputs, I would like a N-column matrix of coordinates and a vector - or `data.frame`, I suppose, to handle multiple attributes - of values. The matrix and the `data.frame` have the same number of rows but are separated to make it easier to distinguish between location and value.

The coordinates themselves would refer to the coordinates of the indexing arguments `i` and `j` and friends, not the coordinates on the full array in `x`. This is important as it disambiguates between duplicated values in `i`. For example, I would like to be able to do this:

```r
# (Ideally, d1 and d2 would be their own matrix or df so that it is easy
# to understand which elements are indices and which are values.
# Nonetheless, I'll show it like this to make it easier to compare with 
# the current state of affairs.)
tiledb_extract_indices(x, i=c(2,2,2,2), j=1)
## $d1
##  [1] 1 2 3 4
##
## $d2
##  [1] 1 1 1 1
##
## $val
##  [1] 2 2 2 2
``` 

From this output, I can easily construct an array or sparse matrix with rows defined by `i` and columns defined by `j`. If I need the full indices (with respect to the entire array), I can simply subset `i` by `d1` and `j` by `d2`. just  In contrast, the current behavior is to do:

```r
A[list(2,2,2,2),list(1)]
## $d1
## [1] 2 2 2 2
## 
## $d2
## [1] 1 1 1 1
## 
## $val
## [1] 2 2 2 2
```

This is harder to reason with because I now need to figure out which of the 2's in `d1` match up with the 2's in the row-subsetting list `i`.
 
Similarly, `tiledb_extract_indices` would be in charge of figuring out how to create a query from arbitrary integer vectors in `i` and `j` and friends. The current state requires me to perform a series of loops to arrange the inputs in the right manner (namely to identify continguous runs and create a list with one entry for the run's start and endpoints), which is unlikely to be efficient.

**Comment by LTLA** [comment]
To expand upon the second point, let's consider the challenge of constructing a sparse matrix corresponding to a submatrix of a sparse **tiledb** dataset. Let's say the desired rows and columns are defined by integer vectors `i` and `j`, respectively. These integer vectors are completely arbitrary - they can be duplicated, they can be out of order, whatever - with the only constraint being that their values lie in `[1, length of corresponding dimension]`.

The simplest way of performing this task is for some function (say, `tiledb_extract_indices`) to return indices and values of non-zero elements, where the indices are defined with respect to the dimensions of the desired submatrix. Then it is a simple matter of just plugging in the indices and values into `Matrix::sparseMatrix` to construct our sparse matrix:

```r
# Arbitrary i and j:
i <- c(2, 1, 5, 2, 3, 4, 1)
j <- c(3, 1, 3)

# Ideally, we would just need to do:
out <- tiledb_extract_indices(A, i=i, j=j)
mat <- sparseMatrix(i=out$d1, j=out$d2, x=out$val, dims=c(length(i), length(j))) 
```

So, if the `(2, 3)` element in the full `A` matrix was non-zero, our `out` would contain multiple copies of its value at the `(d1, d2)` indices of `(1, 1)`, `(4, 1)`, `(3, 1)` and `(4, 3)`.

With the current state of affairs, re-indexing is fairly convoluted:

```r
ui <- unique(i)
uj <- unique(j)
out <- A[as.list(ui), as.list(uj)]

out$d1 <- match(out$d1, ui)
out$d2 <- match(out$d2, uj)
mat0 <- sparseMatrix(i=out$d1, j=out$d2, x=out$val, dims=c(length(ui), length(uj)))

mat <- mat0[match(i, ui), match(j, uj), drop=FALSE]
```

And this is already simplified because **Matrix** subsetting gives us the final step with little work.

**Comment by LTLA** [comment]
I'll continue expanding on the sparse matrix point, because this is probably the most relevant and general use case that, if solved, also solves my problem above. Let me try to formalize this:

## Problem

Given:

- `y`, a sparse matrix in triplet form (`dgTMatrix`)
- `x`, a `tiledb_array` object pointing to a TileDB store containing `y`
- `i`, an integer vector of row indices
- `j`, an integer vector of column indices

What is the easiest way to construct `y[i, j]` from `x`?

## Example code setup

I'll create a scenario for demonstration purposes. First we have `y` and `x`:

```r
set.seed(100)
y <- Matrix::rsparsematrix(10, 10, density=0.5)
y <- as(y, "dgTMatrix")
y
## 10 x 10 sparse Matrix of class "dgTMatrix"
## 
##  [1,] -0.99  .     .     0.61 -0.84  0.53 -0.3500  .      .    -0.28
##  [2,] -1.80  0.48  .     1.70  .     0.21 -0.9600  0.089 -0.28 -2.10
##  [3,]  .     .     0.25  .     0.74  .     1.4000  .      .    -1.10
##  [4,] -0.68 -0.21  0.80  .     .    -1.70  0.9000  0.320  0.60  .
##  [5,]  .     .    -0.71  .    -1.70  0.62  .       .      .    -0.81
##  [6,]  .     1.10  .     .     .     .    -0.0067  .      2.10  .
##  [7,] -0.13  .     .     .     .     .     .      -1.400  .     .
##  [8,]  .     0.87  .     0.55 -1.90  0.93  1.0000 -1.300  0.52 -0.27
##  [9,] -0.98  .     1.30 -1.30  .     .     .       .      0.75  .
## [10,]  .     1.10  0.33  .     .     .     0.2000  .      0.17  .

library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 10L))
d2  <- tiledb_dim("d2", domain = c(1L, 10L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
tiledb_array_create(tmp, sch)

x <- tiledb_array(uri = tmp)
x[] <- data.frame(d1=y@i+1L, d2=y@j+1L, val=y@x)
```

And now let's have `i` and `j`. Note the (lack of) ordering and the presence of duplicates; there is no constraint on the contents of these vectors beyond lying in `[1, length of the dimension]`.

```r
i <- c(1, 5, 3, 10, 2, 1)
j <- c(4, 2, 5, 8, 9, 2)
```

So, the question is, what do I have to do with `x`, `i` and `j` to get the equivalent of `y[i, j]`?

## Current solution

```r
ui <- unique(i)
uj <- unique(j)
# out <- x[as.list(ui), as.list(uj)] # see first bug in original post.
out <- x[list(1, 5, 3, 10, 2), list(4, 2, 5, 8, 9)]

out$d1 <- match(out$d1, ui)
out$d2 <- match(out$d2, uj)
mat0 <- Matrix::sparseMatrix(i=out$d1, j=out$d2, x=out$val, 
    dims=c(length(ui), length(uj)))

mat <- mat0[match(i, ui), match(j, uj), drop=FALSE]
mat
## 6 x 6 sparse Matrix of class "dgCMatrix"
## 
## [1,] 0.61 .    -0.84 .      .    .
## [2,] .    .    -1.70 .      .    .
## [3,] .    .     0.74 .      .    .
## [4,] .    1.10  .    .      0.17 1.10
## [5,] 1.70 0.48  .    0.089 -0.28 0.48
## [6,] 0.61 .    -0.84 .      .    .
```

This took a fair amount of thinking to get to this relatively streamlined piece of code, and it also doesn't work for higher-dimensional sparse arrays. Probably could be more efficient too.

## Desired solution

To construct our sparse matrix easily, we need the following pieces of information:

- `p`, the row index of the non-zero elements with respect to `y[i, j]`.
- `q`, the column index of the non-zero elements with respect to `y[i, j]`.
- `v`, the actual values of the non-zero elements in `y[i, j]`.

The important piece is that the `p` and `q` indices are reported with respect to `y[i, j]`, _not the original sparse matrix `y` that is currently being stored in `x`_. So, for example, I would get:

```r
out <- tiledb_FUNCTION_NAME_HERE(x, i, j)
out
## $p
##  [1] 1 5 6 4 5 1 2 3 6 5 4 5 4 5
## 
## $q
##  [1] 1 1 1 2 2 3 3 3 3 4 5 5 6 6
## 
## $v
##  [1]  0.610  1.700  0.610  1.100  0.480 -0.840 -1.700  0.740 -0.840  0.089
## [11]  0.170 -0.280  1.100  0.480
```

The exact order of the output doesn't really matter, so just ignore that. The important thing is that `p` and `q` don't refer to row/column indices in the original `y` but to the rows and columns in `y[i, j]`. For example, a `q` of 1 corresponds to `j[1]`, i.e., column 4 in the full `y`.

With this output, I can then create the desired sparse matrix simply by calling:

```r
Matrix::sparseMatrix(i=out$p, j=out$q, x=out$v)
```

From the user's perspective, this becomes a two-liner that is pretty intuitive to assemble. Higher-dimensional sparse arrays can also be constructed with this "re-indexed" output.

**Comment by eddelbuettel** [comment]
Ok, the good news is I can get the fourteen desired values out in one query.

**Comment by LTLA** [comment]
Made good progress on `simplified`, but being blocked by some bugs at the edge cases of `tiledb_array`. Currently using the `features/selected_ranges` branch in **TileDB-R**.

## Bug 1

To demonstrate, we'll set up the usual sparse example:

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 10L))
d2  <- tiledb_dim("d2", domain = c(1L, 10L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
tiledb_array_create(tmp, sch)

x <- tiledb_array(uri = tmp)
```

Setters and getters don't like it when there is nothing to set or get. In the code below, we should have some smoother behavior (no-ops for the setter and returning zero-length vectors for the getter) than failing outright.

```r
x[] <- data.frame(d1=integer(0), d2=integer(0), val=numeric(0))
## Error in libtiledb_query_set_buffer_ptr(qryptr, allnames[i], buflist[[i]]) : 
##   [TileDB::Writer] Error: Cannot set buffer; Buffer or buffer size is null
x[]
## Error in libtiledb_query_add_range_with_type(qryptr, 0, dimtypes[1], nonemptydom[[1]][1],  : 
##   [TileDB::Dimension] Error: Range [0, 0] is out of domain bounds [1, 10] on dimension 'd1'
```

Indeed, it's not uncommon to have no entries in the requested set of ranges, which leads to this error even for non-empty arrays:

```r
x[] <- data.frame(d1=1, d2=1, val=1)
x@selected_ranges <- list(cbind(2,2), cbind(2,2))
x[]
## Error in libtiledb_query_set_buffer_ptr(qryptr, name, buf) : 
##   [TileDB::Reader] Error: Cannot set buffer; Buffer or buffer size is null
```

## Bug 2

This is a variant of the previous bug and is somewhat unpredictable, I'm not sure what causes it.

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 100L))
d2  <- tiledb_dim("d2", domain = c(1L, 100L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
tiledb_array_create(tmp, sch)

x <- tiledb_array(uri = tmp)

set.seed(100)
x[] <- data.frame(d1=sample(100, 10, replace=TRUE), d2=sample(100, 10, replace=TRUE), val=1)
x@selected_ranges <- list(cbind(10,10), cbind(10,100))
x[]
## $d1
## [1] 0
## 
## $d2
## [1] 0
## 
## $val
## [1] 0
```

If there are no entries to return, `x[]` should return `integer(0)` rather than `0` in the indices. Perhaps this isn't a bug and is actually intended behavior, but it just makes more sense to return `integer(0)`; then downstream code knows immediately that there are no entries rather than having to go out of its way to check the values.

In my case, this behavior caused unexpected division-by-zero errors in the C++ code because I was expecting `d1` and `d2` to always be a subset of the indices I had specified in `selected_ranges`.

**Comment by eddelbuettel** [comment]
Good stuff.  Bug 1 (part 1) should be easy.  bug 1 (part 2) I noticed myseff yesterday.  I'll look more closely at bug 2 as well.

**Comment by eddelbuettel** [comment]
See [99eb3b7](https://github.com/TileDB-Inc/TileDB-R/commit/99eb3b77561355d2fdf7e4a6d802d93c99f8fb3e) (and [59033f2](https://github.com/TileDB-Inc/TileDB-R/commit/59033f25bfe4d90a327a5c0d66448819a087f1d5)) for bug 1.  The middle part actually exposed a buglet in the C++ layer as we don't signal as well as we should or could when an array is empty.

**Comment by eddelbuettel** [comment]
Bug 2 points to the return from the estimated result size.  It is not signalling 'empty' as in the other cases.  

[3e5236f](https://github.com/TileDB-Inc/TileDB-R/commit/3e5236f6682cbca264ff68f0bcb4da5a88ac6276) works with the current situation but this may need another visit later.

Thanks for both of those reports.  They were excellent.

**Comment by eddelbuettel** [comment]
Actually, bug 2 was just me subsetting the resulting df as  `df[1:resultsize,]` and it it is just about R 101 that this backfires for `resultsize == 0`.  Doh.   Now `df[seq_len(resultsize), ]` and all is good.   See [dc14411](https://github.com/TileDB-Inc/TileDB-R/commit/dc1441127830c76dc09c7eed78e9084d62a6dc54).

**Comment by LTLA** [comment]
Thanks Dirk. With respect to the solution for bug 1 on the latest `features/selected_ranges`, I'm currently getting:

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 100L))
d2  <- tiledb_dim("d2", domain = c(1L, 100L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
tiledb_array_create(tmp, sch)

x <- tiledb_array(uri = tmp)
x[] <- data.frame(d1=1, d2=1, val=1)
x@selected_ranges <- list(cbind(2,2), cbind(2,2))
x[]
## data frame with 0 columns and 0 rows
```

Which is a definite improvement over the previous behavior, but I would argue that the technically correct output would be:

```r
## $d1
## integer(0)
## 
## $d2
## integer(0)
## 
## $val
## numeric(0)
```

as downstream code may behave differently depending on whether it sees `NULL` or an empty vector when doing, e.g., `$d1`. (Incidentally, this is the behavior of the fix for bug 2, which works nicely with the expectations of downstream functions.)

## While we're here... bug 3

On the same theme of edge-case behavior, I have this:

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 100L))
d2  <- tiledb_dim("d2", domain = c(1L, 100L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
tiledb_array_create(tmp, sch)

x <- tiledb_array(uri = tmp)

set.seed(100)
x[] <- data.frame(d1=sample(100, 10, replace=TRUE), d2=sample(100, 10, replace=TRUE), val=1)
selected_ranges(x) <- list(matrix(0, nrow=0, ncol=2), cbind(10,100)) # <-- no ranges on first dimension.
x[]
## $d1
## [1]  4 23 55 70 70 78 86 98
## 
## $d2
## [1] 12 43 99 51 61 55 82 72
## 
## $val
## [1] 1 1 1 1 1 1 1 1
```

It seems that a zero-row matrix is being treated as a `NULL`, but I would argue that a zero-row matrix is asking for "no extraction along that dimension" rather than "give me everything along that dimension". From a practical perspective, the current behavior means that I need to write more protective code around `x[]` to intercept any zero-length indices. 

In this case, it would make more sense for the getter to just return:

```r
## $d1
## integer(0)
## 
## $d2
## integer(0)
## 
## $val
## numeric(0)
```

which spares me from having to maintain the protective code on my end.

**Comment by eddelbuettel** [comment]
>  technically correct output 

If one parses the schema information one getsnames and types and one can build an empty data.frame that matches.  If I find time I may try to build a helper function.  PRs are always welcome too if this is urgent for you.

> a zero-row matrix is asking for "no extraction along that dimension" rather than "give me everything along that dimension". 

Hm, that may be different.  I think that is not what the TileDB API thinks about that request.  

But you can already constrain the result set.  [ Tries. And faills.  Need to take another look. But you can say no to dimensions.Not ideal but works ]

```r
bug3 <- function() {
    tmp <- tempfile()
    dir.create(tmp)

    d1  <- tiledb_dim("d1", domain = c(1L, 100L))
    d2  <- tiledb_dim("d2", domain = c(1L, 100L))
    dom <- tiledb_domain(c(d1, d2))
    val <- tiledb_attr("val", type = "FLOAT64")
    sch <- tiledb_array_schema(dom, c(val), sparse=TRUE)
    tiledb_array_create(tmp, sch)

    x <- tiledb_array(uri = tmp, as.data.frame=TRUE)

    set.seed(100)
    x[] <- data.frame(d1=sample(100, 10, replace=TRUE), d2=sample(100, 10, replace=TRUE), val=1)
    selected_ranges(x) <- list(NULL, cbind(10,100))
    ## so 'by hand' print(x[][,c("d2","val")])
    ## or
    extended(x) <- FALSE
    print(x[])
}
```
